# Generated by Django 6.0.3 on 2026-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
